### ISSUE TITLE
AnyOf title not used

### ISSUE THREAD

**Issue by mbarnach** [mattpolzin/OpenAPIKit#143]
When using the `title` option with an `anyOf`, the title is not saved into the schema.

How to reproduce:

Load any of the 2 following schema (set without the common base document), and try to print the title by:

```swift
let resolvedDoc = try doc.locallyDereferenced().resolved()
if let anyOfSchema = resolvedDoc.routes.first?.endpoints.first?.requestBody?.content.first?.1 {
  print(anyOfSchema.schema.title)
  switch anyOfSchema.schema {
  case .any(let of, let discriminator):
    print(of.map{ $0.title })
  default: break
  }
}
```
But the title of `PetByAge` or `PetByType` will be save.
I suspect this will also be the case for `.oneOf`, `.allOf` and `not`.

Schema 1:

```yaml
paths:
  /pets:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              title: Pets
              anyOf:
                - $ref: '#/components/schemas/PetByAge'
                - $ref: '#/components/schemas/PetByType'
      responses:
        '200':
          description: Updated
components:
  schemas:
    PetByAge:
      title: PetByAge
      type: object
      properties:
        age:
          type: integer
        nickname:
          type: string
      required:
        - age

    PetByType:
      title: PetByType
      type: object
      properties:
        pet_type:
          type: string
          enum: [Cat, Dog]
        hunts:
          type: boolean
      required:
        - pet_type
```

Schema 2:

```yaml
paths:
  /pets:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pets'
      responses:
        '200':
          description: Updated
components:
  schemas:
    Pets:
      title: Pets
      anyOf:
        - $ref: '#/components/schemas/PetByAge'
        - $ref: '#/components/schemas/PetByType'
    PetByAge:
      title: PetByAge
      type: object
      properties:
        age:
          type: integer
        nickname:
          type: string
      required:
        - age

    PetByType:
      title: PetByType
      type: object
      properties:
        pet_type:
          type: string
          enum: [Cat, Dog]
        hunts:
          type: boolean
      required:
        - pet_type
```

**Comment by mattpolzin** [comment]
Indeed. I wonder which keywords in total make sense to parse alongside `anyOf`/`allOf`/`oneOf`/`not`. The JSON Schema specification is, as ever, totally open ended in this respect, but I think that supporting all attributes as a sort of pseudo-`allOf` does not make sense.

It is definitely a good idea to allow meta-data at the parent level (as you noted is currently not possible):
```
schema:
  title: Hello World
  description: A longer string.
  anyOf:
    - type: string
    - type: integer
```

It may even make sense to support the `example` property at the parent level.

Maybe I really should just add the whole `CoreContext` and leave validity checking of things like conflicts between the parent and its composed schemas out of the decoding step.

**Comment by mbarnach** [comment]
I was also thinking of the whole context. I'm currently using the title to generate some content from the specification, and I need to add a hack around any/all of. The whole context would also more flexibility in the future, including indeed the examples.

**Comment by mattpolzin** [comment]
Fixed by version 2.0.0-alpha.3: https://github.com/mattpolzin/OpenAPIKit/releases/tag/2.0.0-alpha.3

Let me know if that closes the gap for you (if you've got time to take a look at the version 2 alpha -- I won't assume you do since the alpha does introduce a handful of breaking changes coming from v1.x).

**Comment by mbarnach** [comment]
Thanks for that.
I've tried the version 2.0.0-alpha.3, but I get the following fatal error: Fatal error: Error raised at top level: The given `all(of:)` schema does not yet support resolving in OpenAPIKit because not, any(of:), all(of:), and one(of:) are not yet supported for schema resolution.
Comming from: https://github.com/mattpolzin/OpenAPIKit/blob/bbbbe5fbfacee3e66fb25d74fac96d0aad6a4a8c/Sources/OpenAPIKit/Schema%20Object/JSONSchema%2BResolving.swift#L74 I think.

**Comment by mattpolzin** [comment]
@mbarnach ah, well thanks for giving it a look. You’ve hit an unrelated limitation that I will have lifted before version 2.0.0 is released. At least, I assume you have a `oneOf`, `allOf`, `anyOf`, or `not` nested within an `allOf` because that’s the only situation where you should see that error right now.

**Comment by mbarnach** [comment]
That's indeed the case. I will see if I can release that limitation for my testing until 2.0 is released. Thanks for pointing me to the right direction!

**Comment by mattpolzin** [comment]
@mbarnach Not at a guaranteed stable v2 API yet (still in alphas) but [alpha 4](https://github.com/mattpolzin/OpenAPIKit/releases/tag/2.0.0-alpha.4) _should_ remove the limitations you were hitting with schema combining types (`all`, `any`, etc.).

This alpha re-introduces `all(of:)` for dereferenced schemas and moves the newer functionality that attempts to combine `all(of:)` schemas into new functions that you can call if you'd like but are not forced into using simply by dereferencing or resolving your document.

**Comment by mbarnach** [comment]
Thanks! It did solve my issue! Looking forward for the release now!
