### ISSUE TITLE
Add support for `default` property on schemas (under one or more of the JSONSchema context types)

### ISSUE THREAD

**Issue by tum-aweink** [mattpolzin/OpenAPIKit#164]
Hey!

Is there a way to get the "default" property (described in [here](https://swagger.io/docs/specification/describing-parameters/) and [here](https://swagger.io/specification/#schema-object)) of a Schema Object?

For example in the swagger PetStoreAPI, the "findPetByStatus" has a parameter "status" of type "string" with a default value of "available":

```
"/pet/findByStatus": {
      "get": {
        "tags": [
          "pet"
        ],
        "summary": "Finds Pets by status",
        "description": "Multiple status values can be provided with comma separated strings",
        "operationId": "findPetsByStatus",
        "parameters": [
          {
            "name": "status",
            "in": "query",
            "description": "Status values that need to be considered for filter",
            "required": false,
            "explode": true,
            "schema": {
              "type": "string",
              "default": "available",
              "enum": [
                "available",
                "pending",
                "sold"
              ]
            }
          }
        ], ...
```

I checked the `StringContext` struct and other properties (min/maxLength & pattern) are defined and can be decoded but the "default" property is missing. Is it planned to include that property or is there a reason why it shouldn't be included?

Thx for your great work!

**Comment by mattpolzin** [comment]
This was an oversight; I was surprised myself to not find `default` anywhere in the `JSONSchema` relevant code. Thank you for bringing it up!

I'll change the title slightly and make this a ticket to add that capability. The question remains (similarly to `example` properties where they are supported by OpenAPIKit) whether it will work best to try to tie the default's type to the type of the schema object or make `default` an `AnyCodable` and require a bit more work to grab a particular type of value out of it.

**Comment by mattpolzin** [comment]
I think we can tie this more closely to the type of the schema. Unlike with `example`, this needs to be the correct type of thing. Examples are complicated because you are allowed to specify them as true schema objects or as string values that decode to schema objects.

**Comment by mattpolzin** [comment]
Hmm, going to have to stick with `AnyCodable` for the default and heed the advice that past myself left when I documented the "allowed values" with:

> NOTE: I would like the default value to have
> the type `Format.SwiftType` but this is not
> tractable because I also want to be able to
> automatically turn any Swift type that will get
> _encoded as something compatible with_
> `Format.SwiftType` into a default.

**Comment by mattpolzin** [comment]
@tum-aweink the default property is now accessible (as of version 2.2.0) under `JSONSchema` or by directly accessing the `CoreContext` of any schema. The property is named `defaultValue`.

**Comment by tum-aweink** [comment]
Thank you @mattpolzin for implementing it!
I tested it on my application and it works perfectly fine.
