### ISSUE TITLE
SwiftUI Previews of OpenAPI Documents

### ISSUE THREAD

**Issue by mattt** [mattpolzin/OpenAPIKit#178]
In the process of working on the Swift package registry specification, I had the idea to create [SwiftUI preview](https://nshipster.com/swiftui-previews/) for OpenAPI documents similar to the [Swagger UI docs](https://petstore.swagger.io). I don't think I'll have an occasion to work on this in the foreseeable future, but I wanted to share this idea in case it strikes you as a useful extension to OpenAPIKit.

**Comment by mattpolzin** [comment]
This is a really cool idea for previewing inside Xcode! Who knows, maybe it could even graduate to a full WASM based web UI in the future!

I also don't know if I'll have time to tackle this feature but I'll cross my fingers that someone else is inspired by the ticket!

I'm not sure if this belongs in this repository or as a curated integration of OpenAPIKit living as its own project but I am happy to grow the idea here regardless.
