### ISSUE TITLE
Add `summary` field to the Info Object

### ISSUE THREAD

**Issue by mattpolzin** [mattpolzin/OpenAPIKit#181]
See the [release notes](https://github.com/OAI/OpenAPI-Specification/releases/tag/3.1.0-rc0), [new spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#fixed-fields), and specifically the [Info Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#info-object).

Work off of the `release/3_0` branch and work on types in the `OpenAPIKit` (not `OpenAPIKit_3_0`) module.

**Comment by mihaelamj** [comment]
@mattpolzin This repo is just what I need for generating the networking layer. Thanks so much for your wonderful work.
I've put up a PR for this:
https://github.com/mattpolzin/OpenAPIKit/pull/206

**Comment by mattpolzin** [comment]
@mihaelamj I'm so glad OpenAPIKit is proving useful to you! Thanks for the contributions!

**Comment by mattpolzin** [comment]
Merged!

**Comment by mihaelamj** [comment]
Thank you!
