### ISSUE TITLE
Add `pathItems` to the Components Object

### ISSUE THREAD

**Issue by mattpolzin** [mattpolzin/OpenAPIKit#183]
See the [release notes](https://github.com/OAI/OpenAPI-Specification/releases/tag/3.1.0-rc0), [new spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#licenseObject), and specifically the [Components Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#components-object).

As far as "good first issues" go, this one is a bit more involved, but everything that needs to be done here has been done for numerous other types that have entries in the Components Object -- feel free to reach out for help by commenting on this ticket if you want to work on it but are getting stuck with the details.

Work off of the `release/3_0` branch and work on types in the `OpenAPIKit` (not `OpenAPIKit_3_0`) module.

**Comment by mihaelamj** [comment]
@mattpolzin Here's a PR for this:
https://github.com/mattpolzin/OpenAPIKit/pull/207
Cheers

**Comment by mattpolzin** [comment]
Merged!
