### ISSUE TITLE
Add support for mutual TLS (mutualTLS) as a security scheme

### ISSUE THREAD

**Issue by mattpolzin** [mattpolzin/OpenAPIKit#189]
See the [release notes](https://github.com/OAI/OpenAPI-Specification/releases/tag/3.1.0-rc0), [new spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md), and specifically the Security Scheme types under [fixed fields](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#fixed-fields-23).

Work off of the `release/3_0` branch and work on types in the `OpenAPIKit` (not `OpenAPIKit_3_0`) module.

**Comment by mihaelamj** [comment]
There are no examples available of `mutualTLS` `Security Scheme Object` type.

Something like this would be useful:
`{
  "type": "mutualTLS"
}`

**Comment by mattpolzin** [comment]
I agree (that an example would be nice)! My interpretation of the specification is that the only Security Scheme Object fields that apply to a type of `"mutualTLS"` are the `type` and `description` and therefore the only two example structures are:
```json
{
  "type": "mutualTLS"
}
```
and 
```json
{
  "type": "mutualTLS",
  "description": "really good authentication"
}
```

**Comment by mihaelamj** [comment]
I can work with that. Thanks.

**Comment by mihaelamj** [comment]
@mattpolzin Here's the PR:
https://github.com/mattpolzin/OpenAPIKit/pull/209
Cheers
