### ISSUE TITLE
Make responses optional under the Operation Object

### ISSUE THREAD

**Issue by mattpolzin** [mattpolzin/OpenAPIKit#193]
See [release notes](https://github.com/OAI/OpenAPI-Specification/releases/tag/3.1.0-rc1), and [new spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md).

Work off of the `release/3_0` branch and work on types in the `OpenAPIKit` (not `OpenAPIKit_3_0`) module.

We need not make the `responses` property optional I don't think; being able to use an empty  response map should be sufficient.

We should make encoding only encode a populated response map, decoding of the `responses` property should be made optional, and the `operationsContainResponses` validation in Validations+Builtins.swift needs to be unincluded in default validations (but still available to optionally include if an end user wants to).

**Comment by mihaelamj** [comment]
@mattpolzin I have started working on this, fyi.

**Comment by mihaelamj** [comment]
@mattpolzin I really would like to make `responses` optional because when you look at any `API` it should reflect its underlying specs. Just looking at the declaration:
`public var responses: OpenAPI.Response.Map?`
needs no explanation.

**Comment by mattpolzin** [comment]
@mihaelamj my thinking on whether a property like a map or array (that can naturally be empty) should be optional as well has thus far been whether there is a meaningful distinction between the empty structure and a `nil` value. if there is a meaningful distinction, it should be optional, otherwise, there should only be 1 way to represent "nothing" -- since we do not currently have "NonEmpty" types in this library, nothing naturally ends up meaning "empty" rather than "nil."

The specification release notes say "responses are no longer required to be defined under the Operation Object." Of course, in JSON, this _could_ be represented by either the absence of the `responses` key altogether or by an empty map. However, in my opinion, the fact that encoding it either way is possible should not be motivation enough to represent it both ways in Swift.

To put it concretely, if a JSON document containing the following:
```json
{
  "something": "Hello",
  "responses": {},
  "another_thing": true
}
```
and one containing no responses key:
```json
{
  "something": "Hello",
  "another_thing": true
}
```
have the same meaning ("there are no responses exposed") then OpenAPIKit _must_ be able to parse both in, but I am ok with OpenAPIKit being _opinionated_ about which of the two ways it is willing to represent things internally and which one it will serialize to. In this case, I think OpenAPIKit should omit the empty responses object when encoding an empty responses map.

There's a usability reason for my opinion, too. When writing Swift code that reads this `responses` property on an `OpenAPI.Operation` value, there needs to be something gained by the distinction between `nil` and empty or else code needs to ignore the difference explicitly or a coder might even wonder what the difference is between the two:
```swift
let operation: OpenAPI.Operation = ...

switch operation.responses {
  case nil: // treat as "no responses"
  case .some(responses):
    if responses.isEmpty {
      // treat as "no responses" (why is this in a different place than
      // the above that also handled "no responses"?)
    } else {
      // treat as "some responses"
    }
}

// alternatively:
guard let responses = operation.responses else {
  // treat as "no responses"
  return
}
// we don't know until we additionally check for non-empty whether 
// we are dealing with "some responses" or "no responses" here so 
// we didn't really gain anything by guarding that it was non-nil above.
```
