### ISSUE TITLE
adopt SSWG security guidelines

### ISSUE THREAD

**Issue by tomerd** [mattpolzin/OpenAPIKit#225]
Hi @mattpolzin, the SSWG recently updated its security guidelines and asks incubating libraries to adopt them.  See for example https://github.com/swift-server/swift-aws-lambda-runtime/pull/209 and https://github.com/mongodb/mongo-swift-driver/pull/640/

**Comment by mattpolzin** [comment]
Sounds good. I’m away on vacation this week so I’ll get updates merged ASAP next weekend!
