### ISSUE TITLE
Different allOf usages

### ISSUE THREAD

**Issue by kean** [mattpolzin/OpenAPIKit#251]
Hey,

I've been adding more specs to the CreateAPI test pool, and found two specs that use the following pattern:

```yaml
UserPoolId:
    allOf:
    - $ref: "#/components/schemas/UserPoolId"
    - description: The Cognito user pool ID for OpenSearch Dashboards authentication.
```

They use `allOf` as a way to add the description to the existing schema. That's not the only creative use of `allOf` construct I found.

If you put this construct in [Swagger Editor](https://editor.swagger.io), it generates the following description:

<img width="394" alt="Screen Shot 2021-12-31 at 1 49 34 PM" src="https://user-images.githubusercontent.com/1567433/147836064-ee06d85a-dfe8-419d-97d0-2f3dfb2d9da0.png">

With OpenAPIKit, when I parse this spec, it creates an object with no properties when only `description` is present. 

I don't have suggestions how to address it yet, but I just wanted to open an issue to keep track of it.

**Comment by mattpolzin** [comment]
I'll take a look into this. I'd certainly expect that allOf to result in a schema representative of the referenced schema + the description.

I think I'd expect it to parse as `allOf [ref, fragment]` and then I would hope that dereferencing gets you to `allOf [string, fragment]` and finally simplifying should get you a string with a description.

**Comment by mattpolzin** [comment]
Tangentially, OpenAPI 3.1 supports an explicit mechanism for overriding (or adding) a description to a ref, but this allOf approach is how I would have thought to accomplish it in v3.0 of the specification.

**Comment by kean** [comment]
Oh, you are right. I just tested it and it does result in a fragment, not an object. My bad, I assumed it was an object because that is what the generated code looked like. I think I misunderstood the idea behind fragments. I'll look a bit more into it. I'm going to close this.
