### ISSUE TITLE
A Sample Implementation of an Authentication

### ISSUE THREAD

**Issue by jcbriones** [mattpolzin/OpenAPIKit#266]
Was trying to figure out how does the security in `OpenAPI.Document.init` works. I was able to create the type of `OpenAPI.SecurityScheme` but I don't know how to add it in the security portion of the init. Can't figure out the correct type to use to initialize it correctly. It would be nice if there is such a documentation in the README.

**Comment by jcbriones** [comment]
Actually was able to figure it out now. But I think it would still be beneficial to add it in readme. I might probably doing it wrong still. Thank you

**Comment by mattpolzin** [comment]
Thanks for letting suggesting better documentation around this!

I've created a PR that I hope adds some clarity that would have been helpful to you if it had been there all along.

If you get the chance, please do let me know if the PR I've opened addresses this issue well enough or not!

https://github.com/mattpolzin/OpenAPIKit/pull/267
