### ISSUE TITLE
Whether Current OpenAPIKit support object type params in query ?

### ISSUE THREAD

**Issue by wangzhizhou** [mattpolzin/OpenAPIKit#288]
```objective-c
  /api/v1/authors:
    get:
      tags:
      - Users
      summary: Returns all users with at least one public project
      description: Returns all users that have at least one public project. Requires
        the `view_public_info` permission.
      operationId: getAuthors
      parameters:
      - name: pagination
        in: query
        description: Pagination information
        required: true
        schema:
          type: object
          properties:
            limit:
              maximum: 25
              minimum: 1
              type: integer
              description: The maximum amount of items to return
              format: int64
              example: 1
            offset:
              minimum: 0
              type: integer
              description: Where to start searching
              format: int64
              example: 0

```

the complete issue as link description: https://github.com/apple/swift-openapi-generator/issues/83

![image](https://github.com/mattpolzin/OpenAPIKit/assets/8174538/721db066-bb40-4bca-a9e4-cf3b877eb468)

**Comment by mattpolzin** [comment]
Yes, OpenAPIKit supports any JSON Schema object for any type of parameter. I am happy to say more about how to use the parameter once OpenAPIKit has parsed it, but based on the issue above I am guessing you are less interested in those details and more interested in how such parameters are surfaced by the swift-openapi-generator project.

**Comment by wangzhizhou** [comment]
> Yes, OpenAPIKit supports any JSON Schema object for any type of parameter. I am happy to say more about how to use the parameter once OpenAPIKit has parsed it, but based on the issue above I am guessing you are less interested in those details and more interested in how such parameters are surfaced by the swift-openapi-generator project.

Thx，the problem is not caused by OpenAPIKit, I will close this issue soon
